Enums with methods
Jij-Inc/pyo3-stub-gen pull request #86
Opened 2024-09-24 12:32 UTC by yamoling

Hello,

I was lacking the possibility of having methods and properties to enums, so here is a proposal that adds this functionality. Additionally, the documentation of documented members is now also present in the ".pyi" output.

Here is a summary of the few changes:
- `MemberInfo` and `MemberDef` have a `doc` and a `is_property` attribute.
- `StubInfoBuilder::add_methods` adds member properties for enums (but not for classes, the behaviour remains the same)
- `StubInfoBuilder::add_methods` now looks for `struct_id` in `module.enum_` in addition to `module.class`.

I would really like these changes to make it to a new release, please let me know if additional changes are required to comply with the current code base.

2024-12-17 21:08 UTC, yamoling commented
Hello @termoshtt,

Is there any progress on this ? Do you need any input from my side ? 
I would really like to merge this feature such that my projects can depend on this repo instead of my current fork.

[Here is an example](https://github.com/yamoling/lle/blob/5b27e4f7bd73366008c29b7fd1f69b84bf214884/python/lle/lle.pyi#L318C1-L318C6) of what the generated pyi looks like in one of my projects (for the `Action` enum class).

Best regards,
  Yannick

2025-02-19 15:17 UTC, yamoling commented
Hello @termoshtt,

I've checked the workflows and addressed all of them except the one on semantic versioning.
Indeed, my changes are breaking in the sense that I've added attributes to the `EnumDef` struct (i.e. `methods` and `members`) and due to the fact that the `EnumDef` struct is publicly constructible (public attributes). Therefore, previous constructions of this structure are made invalid.

That being said, I do not believe that this change requires a major version bump, as there was a single place in the library where the `EnumDef` structure is build and this has been adapted accordingly.

Please let me know your opinion on this.

N.B.: There is a similar discussion for `is_property` and `doc` for `MemberDef` to which my arguments also apply.

2025-03-04 14:26 UTC, yamoling commented
I'm sorry to bother you again, @termoshtt , but could you check this thread again, or at least run the workflows ?
I feel like python enums is actually an important feature, in particular due to how widespread enums are in Rust. 
As I mentioned before, as long as this feature is not merged, I will not be able to rely on the official repo...

2025-04-16 11:57 UTC, termoshtt commented
@yamoling Thanks PR and sorry for long absence. I will review this PR no later than this weekend.

2025-04-19 09:06 UTC, termoshtt requested changes

2025-04-19 09:06 UTC, termoshtt commented on pyo3-stub-gen/src/generate/member.rs
>  }
Inconsistent to `FunctionDef` case

- Use `indent`, do not use raw spaces.
- Use raw string literal `r"""` 
- Add newline after and before `"""`

2025-04-19 09:06 UTC, termoshtt commented on pyo3-stub-gen/src/generate/stub_info.rs
This ad-hoc approach is not the best way, but resolving #74 is not the task of this PR. I will keep this part as it is, and address it in another PR.

2025-04-19 09:11 UTC, termoshtt commented on pyo3-stub-gen/src/generate/stub_info.rs
This will be in the scope of #137

2025-04-19 09:11 UTC, termoshtt commented
This resolves #69

2025-04-23 09:25 UTC, yamoling commented on pyo3-stub-gen/src/generate/stub_info.rs
Ok, then I'll remove the implementation of properties.

2025-04-23 09:40 UTC, yamoling commented on pyo3-stub-gen/src/generate/member.rs
>  }
Ok, done ! 
Thanks for your comments and for taking the time to review this PR :pray:

2025-04-26 06:38 UTC, termoshtt approved these changes
LGTM, Thanks!

2025-04-26 06:38 UTC, merged